<?php
/**
 * Design file upload handling.
 *
 * Customer artwork is uploaded by anonymous visitors, so it is treated as
 * hostile input throughout:
 *
 *  - the on-disk name is generated by us, never taken from the upload;
 *  - only whitelisted extensions are accepted (never .php, never executable);
 *  - files are never linked to directly — they are streamed by a handler that
 *    checks a WooCommerce capability first, so one customer's artwork is not
 *    reachable by guessing a URL;
 *  - the stream always forces a download with a generic content type, so a
 *    crafted SVG or HTML payload cannot execute in an admin's browser session.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Absolute path to the private artwork directory.
 *
 * @return string Trailing-slashed path.
 */
function tfo_get_upload_dir() {
	$uploads = wp_upload_dir();
	return trailingslashit( $uploads['basedir'] ) . 'threadify-order-files/';
}

/**
 * Create the artwork directory and make it as inert as the host allows.
 *
 * The .htaccess only bites on Apache; on nginx (which WordPress.com runs) it is
 * ignored, which is why the extension whitelist — not this file — is the real
 * control keeping executable uploads off disk.
 */
function tfo_prepare_upload_dir() {
	$dir = tfo_get_upload_dir();
	wp_mkdir_p( $dir );

	if ( ! file_exists( $dir . 'index.php' ) ) {
		file_put_contents( $dir . 'index.php', "<?php\n// Silence is golden.\n" );
	}
	if ( ! file_exists( $dir . '.htaccess' ) ) {
		file_put_contents( $dir . '.htaccess', "Deny from all\n" );
	}
}

/**
 * Extensions a customer may send. Deliberately excludes anything the server
 * or a browser could execute.
 *
 * @return string[]
 */
function tfo_get_allowed_extensions() {
	return apply_filters( 'tfo_allowed_extensions', [
		'jpg', 'jpeg', 'png', 'gif', 'webp',
		'pdf', 'ai', 'eps', 'psd', 'svg', 'zip',
	] );
}

/**
 * Maximum accepted artwork size in bytes.
 *
 * Note this is our own ceiling — PHP's upload_max_filesize / post_max_size
 * still apply and may be lower on managed hosting.
 *
 * @return int
 */
function tfo_get_max_upload_bytes() {
	$ours = (int) apply_filters( 'tfo_max_upload_bytes', 25 * MB_IN_BYTES );
	return min( $ours, (int) wp_max_upload_size() );
}

/**
 * Validate a single $_FILES entry.
 *
 * @param array $file Entry from $_FILES.
 * @return true|WP_Error
 */
function tfo_validate_upload( $file ) {

	if ( ! isset( $file['error'] ) || is_array( $file['error'] ) ) {
		return new WP_Error( 'tfo_bad_upload', 'The design file could not be read. Please try again.' );
	}

	switch ( $file['error'] ) {
		case UPLOAD_ERR_OK:
			break;
		case UPLOAD_ERR_NO_FILE:
			return new WP_Error( 'tfo_no_file', 'Please attach your design file.' );
		case UPLOAD_ERR_INI_SIZE:
		case UPLOAD_ERR_FORM_SIZE:
			return new WP_Error( 'tfo_too_large', 'That file is larger than the server accepts. Please send a smaller file, or email it to us.' );
		default:
			return new WP_Error( 'tfo_bad_upload', 'The design file could not be uploaded. Please try again.' );
	}

	if ( ! is_uploaded_file( $file['tmp_name'] ) ) {
		return new WP_Error( 'tfo_bad_upload', 'The design file could not be verified. Please try again.' );
	}

	$max = tfo_get_max_upload_bytes();
	if ( (int) $file['size'] > $max ) {
		return new WP_Error(
			'tfo_too_large',
			sprintf( 'That file is too large (limit %s).', size_format( $max ) )
		);
	}

	$ext = strtolower( pathinfo( $file['name'], PATHINFO_EXTENSION ) );
	if ( ! in_array( $ext, tfo_get_allowed_extensions(), true ) ) {
		return new WP_Error(
			'tfo_bad_type',
			'That file type is not accepted. Please send ' . strtoupper( implode( ', ', tfo_get_allowed_extensions() ) ) . '.'
		);
	}

	// Sniff the real bytes. Blocks a .php or .html payload wearing a .png name.
	if ( function_exists( 'finfo_open' ) ) {
		$finfo = finfo_open( FILEINFO_MIME_TYPE );
		if ( $finfo ) {
			$mime = finfo_file( $finfo, $file['tmp_name'] );
			finfo_close( $finfo );

			$blocked = [ 'text/html', 'text/x-php', 'application/x-httpd-php', 'application/x-executable' ];
			if ( $mime && in_array( $mime, $blocked, true ) ) {
				return new WP_Error( 'tfo_bad_type', 'That file type is not accepted.' );
			}
		}
	}

	return true;
}

/**
 * Move a validated upload into the artwork directory under a name we generate.
 *
 * @param array $file Entry from $_FILES, already passed through tfo_validate_upload().
 * @return array|WP_Error { stored: string, original: string, size: int }
 */
function tfo_store_upload( $file ) {

	tfo_prepare_upload_dir();

	$ext    = strtolower( pathinfo( $file['name'], PATHINFO_EXTENSION ) );
	$stored = wp_generate_password( 32, false, false ) . '.' . $ext;
	$dest   = tfo_get_upload_dir() . $stored;

	if ( ! move_uploaded_file( $file['tmp_name'], $dest ) ) {
		return new WP_Error( 'tfo_store_failed', 'We could not save your design file. Please try again.' );
	}

	@chmod( $dest, 0644 );

	return [
		'stored'   => $stored,
		'original' => sanitize_file_name( $file['name'] ),
		'size'     => (int) $file['size'],
	];
}

/**
 * Resolve a stored filename to a real path inside the artwork directory.
 *
 * Rejects anything that escapes the directory, so a tampered meta value
 * cannot be used to read arbitrary files off the server.
 *
 * @param string $stored
 * @return string|false
 */
function tfo_resolve_stored_path( $stored ) {

	$stored = basename( wp_unslash( $stored ) );
	$base   = realpath( tfo_get_upload_dir() );
	$path   = realpath( tfo_get_upload_dir() . $stored );

	if ( ! $base || ! $path ) return false;
	if ( strpos( $path, $base ) !== 0 ) return false;
	if ( ! is_file( $path ) ) return false;

	return $path;
}

/**
 * Signed, capability-checked download URL for an order item's artwork.
 *
 * @param int $order_id
 * @param int $item_id
 * @return string
 */
function tfo_get_download_url( $order_id, $item_id ) {
	return wp_nonce_url(
		add_query_arg(
			[
				'action'   => 'tfo_download_design',
				'order_id' => (int) $order_id,
				'item_id'  => (int) $item_id,
			],
			admin_url( 'admin-post.php' )
		),
		'tfo_download_' . (int) $item_id
	);
}

// ── Secure download handler ─────────────────────────────────────────
add_action( 'admin_post_tfo_download_design', 'tfo_handle_download' );

function tfo_handle_download() {

	$order_id = isset( $_GET['order_id'] ) ? absint( $_GET['order_id'] ) : 0;
	$item_id  = isset( $_GET['item_id'] )  ? absint( $_GET['item_id'] )  : 0;

	if ( ! $order_id || ! $item_id ) {
		wp_die( 'Invalid request.', 'Invalid request', [ 'response' => 400 ] );
	}

	check_admin_referer( 'tfo_download_' . $item_id );

	$order = wc_get_order( $order_id );
	if ( ! $order ) {
		wp_die( 'Order not found.', 'Not found', [ 'response' => 404 ] );
	}

	// Shop staff only. Artwork belongs to the customer, not the public.
	if ( ! current_user_can( 'edit_shop_order', $order_id ) && ! current_user_can( 'manage_woocommerce' ) ) {
		wp_die( 'You are not allowed to download this file.', 'Forbidden', [ 'response' => 403 ] );
	}

	$item = $order->get_item( $item_id );
	if ( ! $item ) {
		wp_die( 'Line item not found.', 'Not found', [ 'response' => 404 ] );
	}

	$stored   = $item->get_meta( '_' . TFO_FILE_KEY );
	$original = $item->get_meta( '_' . TFO_FILE_KEY . '_name' );

	$path = $stored ? tfo_resolve_stored_path( $stored ) : false;
	if ( ! $path ) {
		wp_die( 'That design file is no longer on the server.', 'Not found', [ 'response' => 404 ] );
	}

	$download_name = $original ?: basename( $path );

	nocache_headers();
	// Generic type + forced attachment: never rendered inline, so a hostile
	// SVG/HTML payload cannot run against an authenticated admin session.
	header( 'Content-Type: application/octet-stream' );
	header( 'Content-Disposition: attachment; filename="' . rawurlencode( $download_name ) . '"' );
	header( 'Content-Length: ' . filesize( $path ) );
	header( 'X-Content-Type-Options: nosniff' );

	if ( function_exists( 'wc_get_logger' ) ) {
		// Leave a trail: artwork access is customer data.
		wc_get_logger()->info(
			sprintf( 'Design file for order #%d item #%d downloaded by user #%d', $order_id, $item_id, get_current_user_id() ),
			[ 'source' => 'threadify-order-options' ]
		);
	}

	readfile( $path );
	exit;
}
